# Generated by Django 4.2.4 on 2023-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('ident', models.IntegerField(verbose_name='Code')),
                ('text', models.CharField(max_length=5000, verbose_name='Text')),
                ('file', models.FileField(upload_to='Files', verbose_name='File')),
                ('date', models.DateTimeField(verbose_name='Time',  auto_now_add=True)),
                ('image', models.FileField(upload_to='Files', verbose_name='Image')),

            ],
        ),
    ]
