# Generated by Django 4.2.4 on 2023-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cloud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Text'),
        ),
    ]
