# Generated by Django 4.2.4 on 2023-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cloud_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
