# Generated by Django 4.2.4 on 2023-09-02 13:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cloud_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='file',
            field=models.FileField(upload_to=main.models.cloud.file_upload_to, verbose_name='File'),
        ),
    ]
